In [57]:
import pandas as pd
training = pd.read_excel('training.xlsx')
scoring = pd.read_excel("scoring.xlsx")
caliData = pd.read_excel(r"C:\Users\user\Documents\Rice-Datathon-2025\cailutility2.xlsx", sheet_name='data')
caliData

,year,Average of avgPriceGasolineUnleadedRegular,Average of avgGasPerThermUSD,Average of avgElecKWHUSD,Average of avgLowSulfurDieselUsdPerGallon
0,1978,0.716917,0.203000,0.041000,NaN
1,1979,0.960750,0.264667,0.040167,NaN
2,1980,1.309833,0.453833,0.067167,NaN
3,1981,1.435917,0.457667,0.077417,NaN
4,1982,1.353250,0.498333,0.093333,NaN
5,1983,1.291583,0.475667,0.076333,NaN
6,1984,1.302083,0.535417,0.084833,NaN
7,1985,1.252083,0.502182,0.098636,NaN
8,1986,0.975750,0.465000,0.084833,NaN
9,1987,0.955000,0.471500,0.082583,NaN
10,1988,1.010583,0.573833,0.092667,NaN
11,1989,1.078250,0.613500,0.102833,NaN
12,1990,1.239917,0.635417,0.110000,NaN
13,1991,1.204417,0.665250,0.123167,NaN
14,1992,1.266083,0.668583,0.125000,NaN
15,1993,1.239833,0.626167,0.131083,NaN
16,1994,1.205000,0.647833,0.130667,1.112900
17,1995,1.217500,0.701000,0.130500,1.109000
18,1996,1.366083,0.538167,0.127500,1.366083
19,1997,1.382250,0.680333,0.127000,1.382250
20,1998,1.239083,0.672667,0.113417,1.239083
21,1999,1.443583,0.709250,0.115000,1.443583
22,2000,1.765417,0.880000,0.115000,1.765417
23,2001,1.733250,1.073750,0.148417,1.733250
24,2002,1.526333,0.729167,0.160250,1.526333
25,2003,1.866750,1.002917,0.156000,1.866750
26,2004,2.113667,1.001667,0.144833,2.113667
27,2005,2.469583,1.327000,0.149417,2.469583
28,2006,2.767583,1.332250,0.184750,2.767583
29,2007,3.094500,1.387750,0.188833,3.094500
30,2008,3.521083,1.538750,0.190667,3.521083
31,2009,2.646750,1.161000,0.209667,2.646750
32,2010,3.067667,1.236667,0.218750,3.067667
33,2011,3.788833,1.295583,0.213000,3.788833
34,2012,4.018750,1.236083,0.213167,4.018750
35,2013,3.859167,1.235750,0.221417,3.859167
36,2014,3.734000,1.424667,0.219833,3.734000
37,2015,3.075833,1.454917,0.218583,3.075833
38,2016,2.711000,1.428000,0.194833,2.711000
39,2017,3.033500,1.486750,0.204250,3.033500
40,2018,3.641833,1.449750,0.209750,3.641833
41,2019,3.705417,1.486333,0.217333,3.705417
42,2020,3.118000,1.615583,0.234917,3.118000
43,2021,4.189333,1.797500,0.256000,4.189333
44,2022,5.550750,2.259333,0.303250,5.550750
45,2023,4.979583,2.089083,0.338500,4.979583
46,2024,4.863500,2.301333,0.396333,4.863500

In [58]:
caliData = caliData.rename(columns={
    'Average of avgPriceGasolineUnleadedRegular': 'avgPriceGasolineUnleadedRegular',
    'Average of avgGasPerThermUSD': 'avgGasPerThermUSD',
    'Average of avgElecKWHUSD': 'avgElecKWHUSD',
    'Average of avgLowSulfurDieselUsdPerGallon': 'avgLowSulfurDieselUsdPerGallon',
    })

In [60]:
training

,Date,Vehicle Category,GVWR Class,Fuel Type,Model Year,Fuel Technology,Electric Mile Range,Number of Vehicles Registered at the Same Address,Region,Vehicle Population
0,2019,P,Not Applicable,Gasoline,2020.0,ICE,Not Applicable,≥4,Statewide,395883
1,2020,P,Not Applicable,Gasoline,2020.0,ICE,Not Applicable,1,Statewide,370954
2,2021,P,Not Applicable,Gasoline,2020.0,ICE,Not Applicable,1,Statewide,349406
3,2019,P,Not Applicable,Gasoline,2019.0,ICE,Not Applicable,≥4,Statewide,348475
4,2019,P,Not Applicable,Gasoline,2018.0,ICE,Not Applicable,≥4,Statewide,333296
...,...,...,...,...,...,...,...,...,...,...
41048,2019,B,Not Applicable,Diesel,1983.0,ICE,Not Applicable,1,Statewide,1
41049,2019,B,Not Applicable,Diesel,1980.0,ICE,Not Applicable,2,Statewide,1
41050,2019,B,Not Applicable,Diesel,1978.0,ICE,Not Applicable,3,Statewide,1
41051,2019,B,Not Applicable,Diesel,1976.0,ICE,Not Applicable,2,Statewide,1
41052,2019,B,Not Applicable,Diesel,1976.0,ICE,Not Applicable,3,Statewide,1

In [61]:
scoring

,Date,Vehicle Category,GVWR Class,Fuel Type,Model Year,Fuel Technology,Electric Mile Range,Number of Vehicles Registered at the Same Address,Region,Vehicle Population
0,2024,P,Not Applicable,Gasoline,2020.0,ICE,Not Applicable,≥4,Statewide,316065
1,2024,P,Not Applicable,Gasoline,2021.0,ICE,Not Applicable,≥4,Statewide,315986
2,2024,P,Not Applicable,Gasoline,2022.0,ICE,Not Applicable,≥4,Statewide,306487
3,2024,P,Not Applicable,Gasoline,2024.0,ICE,Not Applicable,≥4,Statewide,284754
4,2024,P,Not Applicable,Gasoline,2023.0,ICE,Not Applicable,≥4,Statewide,284153
...,...,...,...,...,...,...,...,...,...,...
7541,2024,B,Not Applicable,Diesel,1989.0,ICE,Not Applicable,3,Statewide,1
7542,2024,B,Not Applicable,Diesel,1988.0,ICE,Not Applicable,2,Statewide,1
7543,2024,B,Not Applicable,Diesel,1988.0,ICE,Not Applicable,3,Statewide,1
7544,2024,B,Not Applicable,Diesel,1987.0,ICE,Not Applicable,2,Statewide,1
7545,2024,B,Not Applicable,Diesel,1985.0,ICE,Not Applicable,1,Statewide,1

In [34]:
training = training.rename(columns={
    'Date': 'year',
    'Vehicle Category': 'vehicleCategory',
    'GVWR Class': 'gvwrClass',
    'Fuel Type': 'fuelType',
    "Model Year": "modelYear",
    "Fuel Technology": "fuelTechnology",
    "Electric Mile Range": "electricMileRange",
    "Number of Vehicles Registered at the Same Address": "numVehiclesReg",
    "Vehicle Population:": "vehiclePopulation"
})

scoring = scoring.rename(columns={
    'Vehicle Category': 'vehicleCategory',
    'GVWR Class': 'gvwrClass',
    'Fuel Type': 'fuelType',
    'Model Year': 'modelYear',
    'Fuel Technology': 'fuelTechnology',
    'Electric Mile Range': 'electricMileRange',
    'Number of Vehicles Registered at the Same Address': 'numVehiclesReg',
    'Vehicle Population:': 'vehiclePopulation'
})

training = training.drop(columns=['Region'])
scoring = scoring.drop(columns=['Region'])

In [35]:
# Update missing values in Model Year to use mode from Fuel Type, Fuel Technology subcategories
mode_per_group = training.groupby(["fuelType", "fuelTechnology"])['modelYear'].transform(lambda x: pd.Series.mode(x).iloc[0] if not x.mode().empty else x)
training['modelYear'] = training['modelYear'].fillna(mode_per_group)

In [36]:
# Update unknown values in Electric Mile Range to use mode from Fuel Type, Fuel Technology subcategories
mode_electricMileRange = training.groupby(["year", "vehicleCategory", "fuelType", "fuelTechnology"])['electricMileRange'].transform(lambda x: pd.Series.mode(x).iloc[0] if not x.mode().empty else x)
training['electricMileRange'] = training['electricMileRange'].where(training['electricMileRange'] != 'Unknown', mode_electricMileRange)

In [ ]:
# Update missing values in Model Year to use mode from Fuel Type, Fuel Technology subcategories
mode_per_group_scoring = scoring.groupby(["fuelType", "fuelTechnology"])['modelYear'].transform(lambda x: pd.Series.mode(x).iloc[0] if not x.mode().empty else x)
scoring['modelYear'] = scoring['modelYear'].fillna(mode_per_group_scoring)
# Update unknown values in Electric Mile Range to use mode from Fuel Type, Fuel Technology subcategories
mode_electricMileRange_scoring = scoring.groupby(["year", "vehicleCategory", "fuelType", "fuelTechnology"])['electricMileRange'].transform(lambda x: pd.Series.mode(x).iloc[0] if not x.mode().empty else x)
scoring['electricMileRange'] = scoring['electricMileRange'].where(scoring['electricMileRange'] != 'Unknown', mode_electricMileRange_scoring)

In [ ]:
training

OneHotEncoding

In [38]:
training = pd.get_dummies(training,
                            columns=["gvwrClass", "vehicleCategory", "fuelType", "fuelTechnology", "electricMileRange","numVehiclesReg"],
                            prefix=["gvwrClass", "vehicleCategory", "fuelType", "fuelTech", "electricMileRange", "numVehiclesReg" ],
                            prefix_sep="_")



y_training = training['Vehicle Population']

training['vehicleAge'] = training['year'] - training['modelYear']
training = training.drop(columns=['Vehicle Population'])
if 'fuelType_Unknown' not in training.columns:
    training['fuelType_Unknown'] = 0
    training['fuelType_Unknown'] = 0

In [ ]:
scoring = pd.get_dummies(scoring,
                            columns=["gvwrClass", "vehicleCategory", "fuelType", "fuelTechnology", "electricMileRange","numVehiclesReg"],
                            prefix=["gvwrClass", "vehicleCategory", "fuelType", "fuelTech", "electricMileRange", "numVehiclesReg" ],
                            prefix_sep="_")


scoring['vehicleAge'] = scoring['year'] - scoring['modelYear']
scoring = scoring.drop(columns=['Vehicle Population'])
if 'fuelType_Unknown' not in scoring.columns:
    scoring['fuelType_Unknown'] = 0

In [ ]:
training

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(training, y_training, test_size=0.2, random_state=27)

In [ ]:
from flaml import AutoML

# Initialize AutoML
automl = AutoML()

# Define FLAML settings. Adjust time_budget (in seconds) and metric as needed.
automl_settings = {
    "time_budget": 360,            # total running time in seconds (adjust based on your dataset)
    "metric": 'rmse',             # metric for regression; for classification you might use 'accuracy' or another metric
    "task": 'regression',         # specify the task type: 'regression' or 'classification'
    "log_file_name": "flaml.log", # optional: log file to save training logs
}

# Fit AutoML on the training data
automl.fit(X_train=X_train, y_train=y_train, **automl_settings)

In [ ]:
from sklearn.metrics import mean_squared_error
y_pred = automl.predict(X_test)

# Calculate RMSE (note: mean_squared_error with squared=False gives RMSE)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print("RMSE:", rmse)

# Optionally, you can also compute R² (coefficient of determination)
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R²:", r2)

In [ ]:
import xgboost as xgb
import matplotlib.pyplot as plt

# Extract raw model from FLAML
raw_model = automl.model.model  # Extract from FLAML wrapper

# Plot feature importance
xgb.plot_importance(raw_model)
plt.show()

In [ ]:
from sklearn.inspection import permutation_importance

# Compute permutation importance
result = permutation_importance(raw_model, X_test, y_test, scoring="r2")

# Display importance
import pandas as pd
feature_importance = pd.DataFrame({'Feature': X_test.columns, 'Importance': result.importances_mean})
feature_importance.sort_values(by="Importance", ascending=False, inplace=True)

print(feature_importance)